css header
Keytarina/project-group-22 pull request #17
Opened 2023-02-17 16:04 UTC by Rohochyi

2023-02-17 22:09 UTC, Keytarina requested changes

2023-02-17 22:09 UTC, Keytarina commented on src/partials/header.html
> +<div class="container header">
Зроби контейнер вкладений в хедер (і замість div має бути header). Контейнер потрібний для контенту. Хоча в твому випадку це візуально ніяк не виражається, але, наприклад, якщо б твій хедер мав якийсь background-color, то твій хедер був би обрізаний в межах контейнеру.
![image](https://user-images.githubusercontent.com/59604239/219791433-4958daeb-f34b-44df-96c9-2f0328ce14d2.png)

2023-02-17 22:09 UTC, Keytarina commented on src/partials/header.html
> +            <use href="../img/svg/icons/phone.svg"></use>
шлях має бути "./img/svg/icons/phone.png" і задай клас аби їх можна було стилізувати

2023-02-17 22:09 UTC, Keytarina commented on src/partials/header.html
> +          <use href="../img/svg/icons/phone.svg"></use>
Так само проблема зі шляхом - "./img/svg/icons/phone.png"

2023-02-17 22:09 UTC, Keytarina commented on src/css/header.css
> +  color: #fdfbec;
тут має бути чисто білий колір #fff

2023-02-17 22:09 UTC, Keytarina commented on src/css/header.css
> +  padding-top: 16px;
Задай ще padding-bottom: 9px;

2023-02-17 22:09 UTC, Keytarina commented on src/css/header.css
> +  padding-top: 28px;
Цей padding потрібно задати не списку, а елементу header__link.

2023-02-17 22:09 UTC, Keytarina commented on src/css/header.css
> +  color: #f3c653;
Тут в color замість #f3c653 використовуй змінну var(--accent-color)   (всі змінні є в файлі main.css)

2023-02-17 22:09 UTC, Keytarina commented on src/css/header.css
> +.header__link {
Задай display: block;
І також задай padding-bottom: 16px. Це збільшить область для натискання на сенсорних пристроях. (телефони, планшети)

2023-02-17 22:09 UTC, Keytarina commented on src/css/header.css
> +.heater__list {
Опечатка heater__list заміни t на d
Задай margin-left: auto; Аби список автоматично притиснути до правого боку. Також можеш задати відступи між елементами за допомогою gap: 20px

2023-02-17 22:09 UTC, Keytarina commented on src/css/header.css
> +  line-height: 20px;
Тут неправильно задано line-height, в макеті він 17px

2023-02-17 22:09 UTC, Keytarina commented on src/css/header.css
> +  color: #f3c653;
Тут в color замість #f3c653 використовуй змінну var(--accent-color)   (всі змінні є в файлі main.css)

2023-02-17 22:09 UTC, Keytarina commented on src/partials/header.html
> +    <ul class="heater__list">
Опечатка heater__list заміни t на d

2023-02-17 22:09 UTC, Keytarina commented on src/css/header.css
> +  display: flex;
прибери у контейнера display: flex; Він заважає розташуванню елементів по різні сторони.

2023-02-18 09:41 UTC, Rohochyi commented on src/css/header.css
> +.heater__list {
margin-left: auto не допомогло

2023-02-18 09:42 UTC, Rohochyi commented on src/css/header.css
> +  line-height: 20px;
font-weight: 500;
font-size: 16px;
line-height: 20px;

2023-02-18 09:43 UTC, Rohochyi commented on src/css/header.css
> +  line-height: 20px;
а в мене
 .header__link {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 500;
  font-size: 16px;
  line-height: 1.25;
  letter-spacing: 0.02em;
  color: var(--accent-color)
}

2023-02-18 12:47 UTC, merged